services:
  mongo:
    image: mongo:7.0.14
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: aviationDb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped    
    networks:
      - aviation

  mariadb:
    container_name: mariadb
    image: mariadb:11.2
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=userDb
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - aviation

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - aviation
  
  react:
    container_name: react
    build:
      context: /home/ka3wo/aviation-thesis/aviation-webapp/
    networks:
      - aviation
    depends_on:
      - consul

  consul:
    image: consul:1.15.4
    networks:
      - aviation
    depends_on:
      - mongo
    ports:
      - 8500:8500

  user-service-api:
    container_name: user-service-api
    build:
      context: /home/ka3wo/aviation-thesis/aviation-backend/userservice/
    networks:
      - aviation
    depends_on:
      - consul          
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306                     
      - CONSUL_HOST=consul     
    ports:
      - 8082:8082 

  flight-service-api:
    container_name: flight-service-api
    build:
      context: /home/ka3wo/aviation-thesis/aviation-backend/flightservice/
    networks:
      - aviation
    depends_on:      
      - consul
    environment:
      - CONSUL_HOST=consul
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - 8084:8084
  
  auth-service-api:
    container_name: auth-service-api
    build:
      context: /home/ka3wo/aviation-thesis/aviation-backend/authservice/
    networks:
      - aviation
    environment:      
      - CONSUL_HOST=consul
    depends_on:
      - consul
    ports:
      - 8083:8083
  
  traefik:
    container_name: traefik
    image: traefik:2.11.8
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml
    networks:
      - aviation

networks:
  aviation:
    external: true
