services:
  mongo:
    image: mongo:7.0.14
    container_name: mongo
    ports:
      - 27017:27017    
    environment:
      MONGO_INITDB_DATABASE: aviationDb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./01-mongo.js:/docker-entrypoint-initdb.d/01-mongo.js:ro
    networks:
      - aviation
    
  micronaut:
    container_name: micronaut
    build:
      context: /home/ka3wo/aviation-thesis/aviation-backend/
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    networks:
      - aviation

  react:
    container_name: react
    build:
      context: /home/ka3wo/aviation-thesis/aviation-webapp/
    depends_on:
      - micronaut
    networks:
      - aviation

  traefik:
    container_name: traefik
    image: traefik:2.11.8
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml
    networks:
      - aviation

networks:
  aviation:
    external: true
