services:
  mongo:
    image: mongo:7.0.14
    container_name: mongo
    ports:
      - 27017:27017    
    environment:
      MONGO_INITDB_DATABASE: aviationDb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped
    volumes:
      - ./01-init.js:/docker-entrypoint-initdb.d/01-init.js:ro
    networks:
      - aviation
    
  react:
    container_name: react
    build:
      context: /home/ka3wo/aviation-thesis/aviation-webapp/
    networks:
      - aviation
    depends_on:
      - consul
  
  consul:
    image: consul:1.15.4
    networks:
      - aviation
    depends_on:
      - mongo

  user-service:
    container_name: user-service-api
    build: 
      context: /home/ka3wo/aviation-thesis/aviation-backend/userservice/
    networks:
      - aviation
    depends_on:
      - consul

  flight-service:
    container_name: user-flight-api
    build: 
      context: /home/ka3wo/aviation-thesis/aviation-backend/flightservice/
    networks:
      - aviation
    depends_on:
      - consul

  traefik:
    container_name: traefik
    image: traefik:2.11.8
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml
    networks:
      - aviation

networks:
  aviation:
    external: true
