http:
  routers:
    consul:
      rule: PathPrefix(`/api`)
      service: consul
    react:
      rule: PathPrefix(`/`)
      service: react

  services:
    eureka:
      loadBalancer:
        servers:
          - url: http://consul:8500
    react:
      loadBalancer:
        servers:
          - url: http://react:3002