http:
  routers:
    micronaut:
      rule: PathPrefix(`/api`)
      service: micronaut
    react:
      rule: PathPrefix(`/`)
      service: react

  services:
    micronaut:
      loadBalancer:
        servers:
          - url: http://micronaut:3001
    react:
      loadBalancer:
        servers:
          - url: http://react:3002