http:
  routers:
    consul-router:
        rule: "PathPrefix(`/api/consul/`)"
        service: consul-service
        
    userservice-router:
      rule: "PathPrefix(`/api/user/`)"
      service: user-service

    flightservice-router:
      rule: "PathPrefix(`/api/flight/`)"
      service: flight-service
    
    authservice-router:
      rule: "PathPrefix(`/api/auth/`)"
      service: auth-service

    react-router:
      rule: "PathPrefix(`/`)"
      service: react-service
    
    

  services:
    flight-service:
      loadBalancer:
        servers:
          - url: "http://flight-service-api:8084"
          
    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service-api:8082"


    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service-api:8083"

    react-service:
      loadBalancer:
        servers:
          - url: "http://react:3002"

    consul-service:
      loadBalancer:
        servers:
          - url: "http://consul:8500"
          
